# service-b-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: service-b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SERVICE_NAME
          value: "service-b"
        - name: SERVICE_PORT
          value: "8082"  # Corrected value to be static as "8082"
        - name: CONSUL_HTTP_ADDR
          value: "consul:8500"
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
