version: '3.7'

services:
  consul:
    image: hashicorp/consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    command: 'consul agent -dev -client=0.0.0.0'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8500/v1/status/leader']
      interval: 10s
      timeout: 10s
      retries: 5
